config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :summary, only: [:index]
  resources :students, only: [:index]

  root to: "summary#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :school
  has_and_belongs_to_many :pupils
end

app/models/pupil.rb
class Pupil < ApplicationRecord
  has_and_belongs_to_many :courses
end

app/models/school.rb
class School < ApplicationRecord
  has_many :courses
end

app/models/summary.rb
class Summary < ApplicationRecord

  self.table_name = 'summaries'

  def readonly?
    true
  end

  def self.refresh
    Scenic.database.refresh_materialized_view(table_name, concurrently: false, cascade: false)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :load_data, only: [:index]

  def index
  end

  private

  def load_data
    @schools = School.all
  end

end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController

  def index
    @summary = Summary.all.as_json.first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Statistics', root_path %>
    <%= link_to 'Students', students_path %>
    <hr/>
    <%= yield %>
  </body>
</html>

app/views/pages/stats.html.slim
p
  strong Number of schools:
  br
  = @stats["schools_count"]
p
  strong Average number of courses per school:
  br
  = @stats["courses_avg"]
p
  strong Average number of students per class:
  br
  = @stats["pupils_avg"]

app/views/pages/students.html.slim
- @schools.each do |school|
  div.school
    .column = school.title
    div.courses
      - school.courses.each do |course|
        .column = course.title
        div.pupils
          - course.pupils.each do |pupil|
            .column = pupil.full_name
  br

app/views/students/index.html.slim
- @schools.each do |school|
  div.school
    .column = school.title
    div.courses
      - school.courses.each do |course|
        .column = course.title
        div.pupils
          - course.pupils.each do |pupil|
            .column = pupil.full_name
  br

app/views/summary/index.html.slim
p
  strong Number of schools:
  br
  = @summary["schools_count"]
p
  strong Average number of courses per school:
  br
  = @summary["courses_avg"]
p
  strong Average number of students per class:
  br
  = @summary["pupils_avg"]